#!/bin/bash

echo "Git Hook: Post Checkout"

# Get checkout information
PREVIOUS_HEAD=$1
NEW_HEAD=$2
BRANCH_NAME=$(git branch --show-current)
REPO_NAME=$(basename "$(git rev-parse --show-toplevel)")

MONITOR_DIR="/home/vscode/.vscode-remote/data/Machine/exercise-monitor"
"$MONITOR_DIR/send-dispatch.sh" "post-checkout" '{
    "event_type": "post-checkout",
    "client_payload": {
      "previous_head": "'"$PREVIOUS_HEAD"'",
      "new_head": "'"$NEW_HEAD"'",
      "branch_name": "'"$BRANCH_NAME"'",
      "repository_name": "'"$REPO_NAME"'",
      "timestamp": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
    }
  }'
